# Generated by Django 4.2.7 on 2023-11-02 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0014_alter_subscription_last_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='postAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postTitle',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('S', 'Продам'), ('B', 'Куплю')], default='S', max_length=1),
        ),
    ]
